general {
    col.active_border = rgba(475248ee) rgba(4f5b50ee) 45deg
    col.inactive_border = rgba(7fbbb3ee)
}

decoration {
    shadow {
    	color = rgba(d699b677)
    	color_inactive = rgba(7fbbb377)
    }
}
