windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrulev2 = float, class:^(hyprland-run)$
windowrulev2 = move 20 100%-120, class:^(hyprland-run)$

windowrulev2 = float, class:^(warpaper_live)$
windowrulev2 = pin, class:^(warpaper_live)$
windowrulev2 = noshadow, class:^(warpaper_live)$
windowrulev2 = nofocus, class:^(warpaper_live)$
windowrulev2 = noinitialfocus, class:^(warpaper_live)$
windowrulev2 = noanim, class:^(warpaper_live)$
windowrulev2 = size 100% 100%, class:^(warpaper_live)$
windowrulev2 = center, class:^(warpaper_live)$
windowrulev2 = noblur, class:^(warpaper_live)$
windowrulev2 = nodim, class:^(warpaper_live)$

windowrulev2 = float, class:^(volumemixer)$
windowrulev2 = size 700 400, class:^(volumemixer)$
windowrulev2 = center, class:^(volumemixer)$

#layerrule = blur, swaync-control-center
#layerrule = ignorezero, swaync-control-center
#layerrule = ignorealpha 0.5, swaync-control-center

