general {
    col.active_border = rgba(bd93f9ee) rgba(ff79c6ee) 45deg
    col.inactive_border = rgba(8be9fdee)
}

decoration {
    shadow {
    	color = rgba(bd93f977)
    	color_inactive = rgba(8be9fd77)
    }
}
