general {
    col.active_border = rgba(cba6f7ee) rgba(cdd6f4ee) 45deg
    col.inactive_border = rgba(89dcebee)
}

decoration {
    shadow {
    	color = rgba(cba6f777)
    	color_inactive = rgba(89dceb77)
    }
}
